### ISSUE TITLE
Cannot save course score

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#138]
## Tasks
- [x] Change `Songs` collection definition
- [x] Merge `Courses` collection into `Songs` collection
- Fix Song API to ignore course data
  - [x] Get Song Information
  - [x] Search Song by Series
  - [x] Search Charts
- Fix Course API
  - [x] Get Course Information
  - [x] Get Course List
- Move /Courses data to /Songs
  - [x] Staging
  - [x] Production
