### ISSUE TITLE
Create manual for DDRadar

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#195]
## Tasks
- [ ] User Registration / ユーザー登録
- [ ] Input Score / スコア登録
- [ ] Import Scores / スコアインポート
- [ ] Groove Radar / グルーブレーダー
