### ISSUE TITLE
Import score from Skill Attack

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#196]
## Tasks
- [x] Create "Import Skill Attack ID to DB" batch (#265)
- [x] Support `skillAttackId` on "Import Song Scores" API (#266)
- [x] `score_00000000.txt` converter on client (#268)

## Ref
- http://skillattack.com/sa4/data/master_music.txt
- http://skillattack.com/sa4/data/dancer/11173996/score_11173996.txt
