### ISSUE TITLE
Road map for v1

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#21]
## [v0.1](https://github.com/ddradar/ddradar/milestone/2) (API side) (#14)
- [x] Authentication API (built-in) `/.auth/` (#20)
- Song API
  - [x] Get Song Info `/api/v1/songs/{:id}` (#15)
  - [x] Post Song Info `/api/v1/admin/songs` (#28)
  - [x] Search Song `/api/v1/songs/name/{:index}`, `/api/v1/songs/series/{:index}` (#16, #22)
  - [x] Search Charts `/api/v1/charts/{:playStyle}/{:level}` (#25)
- Course API
  - [x] Get Course Info (#24)
  - [x] Get Course List (#26)

## [v0.2](https://github.com/ddradar/ddradar/milestone/4) (Client side) (#75)
- Page Design
  - [x] Layout (#30)
  - [x] Logo (#74)
- Song Page
  - [x] Song List `/name/{:index}`, `/series/{:index}` (#53, #54)
  - [x] Chart List `/single/{:level}`, `/double/{:level}` (#56)
  - [x] Song Details `/songs/{:id}` (#49)
- [x] Admin Song Editor `/admin/song` (#57)
- [x] Error Page (#69)

## [v0.3](https://github.com/ddradar/ddradar/milestone/5) (API side) (#88)
- User API
  - [x] Get User Info `/api/v1/users/{:id}` (#79)
  - [x] Get Current User `/api/v1/user` (#80)
  - [x] Post User Info `/api/v1/user` (#81)
  - [x] Get User List `/api/v1/users` (#84)

## [v0.4](https://github.com/ddradar/ddradar/milestone/6) (Client side)
- User Page
  - [ ] User List `/users`
  - [ ] User Info `/users/{:id}`
  - [x] Settings `/profile` (#94)

## v0.5 (API side)
- Score API
  - [ ] Get User Score
  - [ ] Get Score for Leader-board
  - [ ] Post User Score (single)
  - [ ] Post User Score (multiple)

## v0.6 (Client side)
- [ ] Total User Score
- [ ] Leader-board
- [ ] Score Editor
- [ ] Score Importer

**Comment by nogic1008** [comment]
moved projects
