### ISSUE TITLE
Publish @ddradar/core package to GitHub Packages

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#449]
## Tasks
- [x] setup `@ddradar/core` build process
- [x] setup GitHub Packages
- [x] use GitHub Packages on CI build
- add `@ddradar/core` package
  - [x] API
  - [x] Functions 
- remove Symbolic links for `/core`
  - [x] API
  - [x] Functions
