### ISSUE TITLE
[BUG] Skill Attack Import Issues

### ISSUE THREAD

**Issue by signoiidx** [ddradar/ddradar#623]
## Actual Behavior / 問題の概要

- When Importing Skill Attack data, DDR-A-deleted song "女々しくて" can't load and says "Not Found."

## Actual Screenshot / スクリーンショット

- Here shows "女々しくて" issue.
https://gyazo.com/2c8ce31c2ae0b4ccd2c94d6365a25187

## Excepted Behavior / 本来どのように動作すべきか

- When importing system encounter deleted songs, it ignore certain data.

## How to Reproduce / 再現手順

1. Go to 'My Page'
2. Click on 'Score Import'
3. Click on 'Select File'
4. Select 'Skill Attack text data including 女々しくて'
(https://gist.github.com/signoiidx/c86da631a9487d3c34396a20996c2375)
5. See error 'Not Found'

# Environment / 動作環境

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser / ブラウザ: FireFox
 - Browser Version / ブラウザのバージョン: 89.0.1

**Additional context**
- The following URL is the data without "女々しくて"
(https://gist.github.com/signoiidx/066fcc88929ac85187a55f113fd1f180)
- DDR A deleted music list
Other songs might have same issue but my data cannot verify.
(https://bemaniwiki.com/index.php?DanceDanceRevolution%20A/%BA%EF%BD%FC%B6%CA%A5%EA%A5%B9%A5%C8#ae0b7037)
- DDR A20 deleted musics loaded correctly. (eg. More One Night, ジャパリパーク)

**Comment by nogic1008** [comment]
@signoiidx 
Thank you for your report!

It is caused by no master data, so we can also solve it by simply adding song info.
But we need to disable "Import" button at deleted song detail page. (`/songs/{songId}`)

**Comment by nogic1008** [comment]
I decided to add song info that deleted at DDR A version.
However, it is not desirable that those charts are counted as "NO PLAY".
Therefore, I will fix counting methods (includes A20/A20 PLUS deleted songs).

-----

DDR Aで削除された楽曲の情報を追加することにしました。
しかし、それらが「NO PLAY」として集計されてしまうのは望ましくありません。
そのため、(A20/A20 PLUS削除曲を含む)それらをカウントしないよう修正します。

-----
## Tasks
- [x] Add Song Data (Today)
- [ ] Fix Counting Methods (Next Week?)
- [ ] Disable "Import" Button on deleted song (Next Week?)

**Comment by nogic1008** [comment]
P.S. There are no plans to add song info on deleted before DDR 2014 because the judgment timing is too different.

----

追記: 判定タイミングが違いすぎるため、DDR2014以前の曲情報を追加する予定はありません。

**Comment by nogic1008** [comment]
Added these songs.
But "Import Skill Attack Id" Job launches every 2:00 AM (UTC).
So please wait next 11:00 AM (JST).

-----

これらの楽曲を追加しました。
しかし、「Skill AttackのIDをインポートする」ジョブは毎日AM2:00(UTC)に実行されます。
明日のAM11:00(日本時間)までお待ちください。

- KUNG FU FIGHTING
- BAD GIRLS
- Boom Boom Dollar (Red Monster Mix)
- stomp to my beat
- ポリリズム
- Trickster
- IF YOU WERE HERE
- IF YOU WERE HERE (L.E.D.-G STYLE REMIX)
- LOVE & JOY
- 折れないハート
- ジョジョ～その血の運命～
- ふりそでーしょん
- Burst The Gravity
- Choo Choo TRAIN
- LOVE & JOY -Risk Junk MIX-
- Mickey Mouse March(Eurobeat Version)
- 女々しくて
- future gazer
- STRAIGHT JET
- Strobe♡Girl

**Comment by nogic1008** [comment]
Now, this issue is resolved. (tested on my Skill Attack data)
I have divided into #625 the issue caused by adding the deleted song.
