### ISSUE TITLE
Create Project Logo

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#68]
## Tasks
- [x] [Organization](https://github.com/ddradar)
- [x] Social preview on ddradar/ddradar
- `/client` (#74)
  - [x] [Navbar](https://github.com/ddradar/ddradar/blob/master/client/layouts/default.vue)
  - [x] [favicon](https://github.com/ddradar/ddradar/blob/master/client/static/favicon.ico)
  - [x] PWA image
