### ISSUE TITLE
Support DDR A3 e-amusement Site

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#862]
Implemented after プレーデータ閲覧(View play data) is released
- https://p.eagate.573.jp/game/ddr/ddra3/p/info/index.html#info001a
## Tasks
- [x] Add "Dance Dance Revolution A3" on `Series` (#866)
- Implement HTML parser for new e-amusement site
  - [x] `@ddradar/core` (#887)
  - [x] bookmarklet (/client/static/eagate.js) (#888)
- [x] Change direct link to DDR A20 site (#888)
- [x] `@ddradar/script` (#893)
- [x] Change "B4U (The Acolyte mix)" song id (#890)
