### ISSUE TITLE
"B4U (The Acolyte mix)"'s `songId` changed on DDR A3

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#890]
- **Before**: dll9D90dq1O09oObO66Pl8l9I9l0PbPP
- **After**: 01lbO69qQiP691ll6DIiqPbIdd9O806o

## Tasks
- [x] Create `01lbO69qQiP691ll6DIiqPbIdd9O806o` song document
- [x] Change user score's `songId`
- [x] Remove old song document
- [x] Transfer old `songId` to new one (#891)
