### ISSUE TITLE
Migrate to Nuxt 3

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#931]
## API
- [x] GET `/charts/:style/:lv` (#979)
- [x] GET `/courses` (#979)
- [x] GET `/courses/:id` (#948)
- [x] GET `/notification` (#979)
- [x] POST `/notification` (#979)
- [x] GET `/notification/:id` (#979)
- [x] POST `/scores/:id` (#979)
- [x] DELETE `/scores/:id/:style/:diff` (#979)
- [x] GET `/scores/:id/:style/:diff` (#979)
- [x] POST `/scores/:id/:style/:diff` (#979)
- [x] GET `/scores/:uid` -> `/users/:id/scores` (#979)
- [x] GET `/songs` (#948)
- [x] POST `/songs` (#948)
- [x] GET `/songs/:id` (#948)
- [x] GET `/user` (#948)
- [x] POST `/user` (#979)
- [x] GET `/users` (#979)
- [x] GET `/users/:id` (#979)
- [x] GET `/users/:id/clear` (#979)
- [x] GET `/users/:id/exists` (#979)
- [x] GET `/users/:id/radar/:style` -> `/users/:id/radar` (#979)
- [x] GET `/users/:id/score` -> `/users/:id/rank` (#979)
## Web Page
- [x] /:style/:level -> /charts (#987)
- [x] /admin/notification/:id (#1157)
- [x] /admin/song/:id (#1084)
- [x] /courses/:id (#980)
- [x] /grade/:series -> /courses?type=2 (#980)
- [ ] /help
- [x] /name/:index -> /songs?name= (#980)
- [x] /nonstop/:series -> /courses?type=1 (#980)
- [x] /series/:index -> /songs?series= (#980)
- [x] /songs/:id (#980)
- [x] /users (#1144)
- [x] /users/:id (#1144)
- [ ] /users/:id/scores
- [ ] /import
- [ ] /index
- [x] /notification (#1156)
- [x] /profile (#1155)
