### ISSUE TITLE
[New Songs] 東方ユーロビート祭り

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#95]
## Tasks
- [x] Crazy Hot / NJK Record feat.nachi
- [x] GUILTY DIAMONDS / SOUND HOLIC Vs. Eurobeat Union feat. Nana Takahashi
- [x] No Life Queen [DJ Command Remix] / SOUND HOLIC Vs. Eurobeat Union feat. Nana Takahashi
- [x] Together Going My Way / DiGiTAL WiNG with 空音
- [x] Feidie / A-One feat.Napoleon
-----
## Crazy Hot
- **Song Id:** dq6b0b6OD9DbDPQOO608oDo8Q80ODIqO
- **Artist / アーティスト:** NJK Record feat.nachi
- **Furigana / 読み仮名:** CRAZY HOT
- **Series Folder / シリーズ:** DanceDanceRevolution A20 PLUS
- **BPM:** 162
#### Single
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BEGINNER|3|110|13|0|19|13|3|24|0|
|BASIC|6|230|13|0|40|26|21|24|0|
|DIFFICULT|10|337|24|0|59|47|23|31|14|
|EXPERT|13|450|28|0|79|67|50|34|57|
#### Double
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BASIC|6|230|14|0|40|26|18|29|0|
|DIFFICULT|10|337|24|0|59|47|23|31|14|
|EXPERT|13|442|28|0|78|67|40|34|50|
-----
## GUILTY DIAMONDS
- **Song Id:** QbdQold98oq9lODoIloIbPiIqld6i0Qb
- **Artist / アーティスト:** SOUND HOLIC Vs. Eurobeat Union feat. Nana Takahashi
- **Furigana / 読み仮名:** GUILTY DIAMONDS
- **Series Folder / シリーズ:** DanceDanceRevolution A20 PLUS
- **BPM:** 84-168
#### Single
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BEGINNER|3|113|10|0|18|13|3|16|0|
|BASIC|6|276|16|0|44|41|10|45|1|
|DIFFICULT|10|358|26|0|57|47|32|71|17|
|EXPERT|14|472|32|0|75|75|38|71|53|
#### Double
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BASIC|6|274|16|0|44|34|9|45|1|
|DIFFICULT|10|358|26|0|57|47|30|71|17|
|EXPERT|14|475|32|0|76|75|29|71|52|
-----
## No Life Queen [DJ Command Remix]
- **Song Id:** I9P1dbOqD1qIP8bd9O80Ooo869bldobD
- **Artist / アーティスト:** SOUND HOLIC Vs. Eurobeat Union feat. Nana Takahashi
- **Furigana / 読み仮名:** NO LIFE QUEEN DJ COMMAND REMIX
- **Series Folder / シリーズ:** DanceDanceRevolution A20 PLUS
- **BPM:** 165
#### Single
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BEGINNER|3|124|2|0|21|20|1|7|0|
|BASIC|7|270|8|0|46|34|10|15|1|
|DIFFICULT|11|435|4|0|74|55|16|5|33|
|EXPERT|14|609|21|0|108|89|25|15|101|
#### Double
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BASIC|7|268|8|0|46|34|3|18|1|
|DIFFICULT|11|432|4|0|74|55|10|5|33|
|EXPERT|14|599|15|0|106|82|16|12|101|
-----
## Together Going My Way
- **Song Id:** POdll6oPi1dd68q19q8ID6iQ6d08bl99
- **Artist / アーティスト:** DiGiTAL WiNG with 空音
- **Furigana / 読み仮名:** TOGETHER GOING MY WAY
- **Series Folder / シリーズ:** DanceDanceRevolution A20 PLUS
- **BPM:** 155
#### Single
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BEGINNER|2|78|5|0|16|12|1|22|0|
|BASIC|5|139|9|0|29|25|7|30|0|
|DIFFICULT|9|243|42|0|51|45|27|58|14|
|EXPERT|13|340|25|0|71|64|38|37|56|
#### Double
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BASIC|5|139|8|0|29|25|3|28|0|
|DIFFICULT|9|240|42|0|50|45|23|58|13|
|EXPERT|13|346|27|0|73|64|21|38|57|
-----
## Feidie
- **Song Id:** DDPPI6IIi0i9looibDbiODoOPOl6ID8i
- **Artist / アーティスト:** A-One feat.Napoleon
- **Furigana / 読み仮名:** FEIDIE
- **Series Folder / シリーズ:** DanceDanceRevolution A20 PLUS
- **BPM:** 150
#### Single
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BEGINNER|2|79|9|0|15|12|3|20|0|
|BASIC|6|217|5|0|41|31|29|12|0|
|DIFFICULT|8|261|10|0|50|37|29|18|10|
|EXPERT|10|324|12|0|62|50|40|18|22|
#### Double
|Difficulty|Lv|Notes|FA|SA|Str|Vol|Air|Fre|Cha|
|:---------|--:|--:|--:|--:|--:|--:|--:|--:|--:|
|BASIC|6|217|5|0|41|31|36|12|0|
|DIFFICULT|8|261|10|0|50|37|27|18|10|
|EXPERT|10|321|12|0|61|50|38|18|22|
-----

### Reference Data/参考データ
- https://p.eagate.573.jp/game/ddr/ddra20/p/info/index.html#info45

**Comment by nogic1008** [comment]
Added Staging & Production
